spring.application.name=sistema

spring.datasource.url = jdbc:mysql://acela.proxy.rlwy.net:36635/sistema_horarios

spring.datasource.username=root
spring.datasource.password=cjPMWgGvXRgSKhRYqbpWQmlOGupQXFpn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.user.datasource.driver-class-name=com.mysql.jdbc.driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true